`timescale 1ns/1ps

// tb_imem -- self-checking testbench for rtl/imem.v.
// Instantiates with INIT="asm/smoke.hex" (generated by tools/asm.py from
// asm/smoke.s) and checks synchronous reads against hardcoded expected words
// (the first four lines and the last line of asm/smoke.hex), en=0 hold
// behavior, and address-wrap (bits above 11 ignored).
module tb_imem;

    reg         clk;
    reg         en;
    reg  [31:0] addr;
    wire [31:0] inst;

    integer checks;
    integer failures;

    imem #(.INIT("asm/smoke.hex")) dut (
        .clk(clk),
        .en(en),
        .addr(addr),
        .inst(inst)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    task chk;
        input [31:0] got;
        input [31:0] exp;
        input [255:0] msg;
        begin
            checks = checks + 1;
            if (got !== exp) begin
                failures = failures + 1;
                $display("FAIL check: %0s got=%08x exp=%08x", msg, got, exp);
            end
        end
    endtask

    initial begin
        checks = 0;
        failures = 0;
        en = 0;
        addr = 32'h0;

        // ---- word 0: line 1 of asm/smoke.hex = 00001137 (lui sp,1) ----
        @(negedge clk);
        en = 1;
        addr = 32'd0;
        @(posedge clk);
        #1;
        chk(inst, 32'h00001137, "word 0");

        // ---- word 1: line 2 = 00010113 (addi sp,sp,0) ----
        @(negedge clk);
        addr = 32'd4;
        @(posedge clk);
        #1;
        chk(inst, 32'h00010113, "word 1");

        // ---- word 2: line 3 = 00000297 (auipc t0,0) ----
        @(negedge clk);
        addr = 32'd8;
        @(posedge clk);
        #1;
        chk(inst, 32'h00000297, "word 2");

        // ---- word 3: line 4 = 00000337 (lui t1,0) ----
        @(negedge clk);
        addr = 32'd12;
        @(posedge clk);
        #1;
        chk(inst, 32'h00000337, "word 3");

        // ---- word 1023: last line of asm/smoke.hex = 00000000 (zero padding) ----
        @(negedge clk);
        addr = 32'd1023 * 4;
        @(posedge clk);
        #1;
        chk(inst, 32'h00000000, "word 1023");

        // ---- en=0 holds previous output while addr changes ----
        @(negedge clk);
        addr = 32'd0; // back to word 0, but en will be 0
        en = 0;
        @(posedge clk);
        #1;
        chk(inst, 32'h00000000, "en=0 holds previous output (1)");
        @(negedge clk);
        addr = 32'd4;
        @(posedge clk);
        #1;
        chk(inst, 32'h00000000, "en=0 holds previous output (2), addr changed");

        // ---- resume with en=1, confirm normal read still works ----
        @(negedge clk);
        en = 1;
        addr = 32'd0;
        @(posedge clk);
        #1;
        chk(inst, 32'h00001137, "resume en=1 reads word 0 again");

        // ---- addr bits above 11 ignored: addr=0x1000 reads word 0 ----
        @(negedge clk);
        addr = 32'h00001000;
        @(posedge clk);
        #1;
        chk(inst, 32'h00001137, "addr=0x1000 wraps to word 0");

        // and addr=0x1004 (0x1000 + word1 offset) should read word 1
        @(negedge clk);
        addr = 32'h00001004;
        @(posedge clk);
        #1;
        chk(inst, 32'h00010113, "addr=0x1004 wraps to word 1");

        if (failures == 0) begin
            $display("PASS: tb_imem (%0d checks)", checks);
        end else begin
            $display("FAIL: tb_imem (%0d failures)", failures);
        end
        $finish;
    end

endmodule
